export const practiceAreas = [
  {
    id: "corporate-commercial",
    title: "Corporate and Commercial",
    description: "The department understands both the complexities and the skills required to provide an efficient and effective service to our clients in relation to corporate and commercial law transactions.",
    details:
      "We are well placed to provide complete advice across all practice areas of commercial transactions including on all legal, regulatory, and tax aspects of investing and establishing operations in Kenya. We pride ourselves in our ability to provide prompt and high-quality services to our clients commensurate to their respective business needs. We provide legal advice and related services on a wide range of commercial matters including:",
    services: [
      "General corporate, commercial and contract briefs",
      "Company Secretarial",
      "Mergers and Acquisitions",
      "Joint Ventures",
      "Corporate Finance and Securitization",
      "Corporate restructuring",
      "Franchising",
      "Legal Compliance & Corporate Governance Audit",
      "Tax law advisory",
      "Immigration Law services and advisories",
      "Competition law advisory",
      "Projects & Infrastructure",
      "Capital Markets and Securities law",
      "Public-Private Partnerships",
      "Mining",
      "Energy, Oil and Gas law",
    ],
    sectorExpertise: [],
  },
  {
    id: "dispute-resolution",
    title: "Dispute Resolution",
    description: "With the client's specific business or other objectives at the top of our mind, this department focuses on dealing with disputes that may arise or have arisen in an efficient and effective manner whilst drawing upon our extensive experience, trusted judgment, and insight to develop a customized strategy for each case.",
    details: "Our dispute resolution lawyers employ the most appropriate tools and strategies for each stage of the process and each unique situation. Apart from having an amazing track record for conducting successful trials in the courtroom, the department is equally well equipped with knowledge and skills in handling legal matters out of the courtroom either through negotiations, mediation, or arbitration. The department has a pool of knowledge and expertise in dispute resolution mechanisms such as litigation, domestic and international arbitrations, negotiation, and mediation having settled complex disputes involving commercial transactions. Practice before international courts and tribunals like the East African Court of Justice (EACJ), the International Court of Justice (ICJ), the International Criminal Court (ICC), the African Court on Human and Peoples' Rights (AfCHPR) as well as other international courts and tribunals squarely find accommodation in this department.",
    services: [
      "Commercial litigation and arbitration",
      "Aviation disputes",
      "Partnership and Shareholders'/Directors' disputes",
      "Family and Succession law",
      "Land and environmental disputes",
      "IntellectuaWe provide an array of high-quality services to clients within the technology, media, and telecommunications industries. We provide strategic commercial advice to a wide range of industry sectors in regard to technology and intellectual property law with a consistent level of attention to detail, client service, efficiency, and a deep understanding of our client's objectives.",
    details: "Technological advancement has brought to the fore the dire need to protect and safeguard numerous inventions for purposes of proper utilization. Intellectual Property has become one of the most critical legal areas as companies and individuals continue to expand and protect their technology, brands, products, data, and services all over the world. In this regard, being well-versed with the requirements of protection and proper utilization of technology, the Firm provides a full range of media law, intellectual property law, privacy, and technology law services for both individuals and businesses within the region. We have demonstrated a solid and indisputable track record of representation of our clients in Trade Marks, Copyrights, Utility Models, Industrial Designs, and Patents whether before Kenya Industrial Property Institute (KIPI), African Regional Property Institute (ARIPO), or the World Intellectual Property Organization (WIPO). We have had a stellar performance in national jurisdiction-based IP protection in countries like Ghana, Ethiopia, the Federal Republic of Nigeria, and the United Republic of Tanzania.
      "Banking law and banking securities enforcement",
      "Insurance litigation",
      "Corporate Insolvency disputes",
      "Constitutional and Judicial Review litigation",
      "Electoral disputes",
      "Public Procurement related disputes",
      "Medical Negligence suits",
      "Criminal and Civil litigation",
    ],
    sectorExpertise: [],
  },
  {
    id: "media-tech-ip",
    title: "Media, Technology & Intellectual Property",
    description: "[Insert short introductory paragraph here]",
    details: "[Insert supporting paragraph here]",
    services: [],
    sectorExpertise: [],
  },
  {
    id: "energy-climate",
    title: "Energy, Natural Resources & Climate Change",
    description: "The Firm has developed in-depth sector know-how and has the ability to provide innovative and cutting-edge solutions to clients within the energy, natural resources, and climate change sector. Indeed, the Firm provides a range of services related to energy, natural resources, environmental law, and climate change sectors. The Firm has acted for various renewable energy firms and oil and gas entities.",
    details: "We have provided advisory and drafting services in relation to the exploration, development, and operationalization of oil and gas properties, including concession, drilling, development, production-sharing, joint-venture and operating agreements. Further to the foregoing, the Firm has developed extensive knowledge in environmental issues including climate change and other sustainability issues, green building financing, carbon trading and construction standards and practices, low impact development, and renewable energy. Our Team provides legal services to a wide range of National and County Governments, government entities, and non-state actors on the regulatory framework for environmental and climate change.",
    services: [],
    sectorExpertise: [],
  },
  {
    id: "real-estate-finance",
    title: "Real Estate, Banking & Finance",
    description: "The Firm has extensive knowledge and experience in providing excellent services to clients in a wide range of proprietary transactions. We pride ourselves in giving our clients quality legal advice based on sound due diligence in an area where utmost caution and efficiency are encouraged.",
    details: "Some of the services we provide in this department include: General banking and investment structures; Project Finance, Infrastructure and Construction; Structuring and perfection of security documentation in favor of lending/finance institutions such as charges, musharakah, debentures, guarantees, indemnities, loan agreements and deeds of assignments; Debt structuring; Lending and syndicated lending; Advisories on securitization and asset-backed securities, project financing and securities review; Islamic Banking and Finance (Takaful); Construction law and advisory; Legal advisory services to real estate developers, investors and purchasers in the acquisition, development, financing, sale and(sub) leasing of real estate, drafting and review agreements for sale, transfers, (sub) leases, novation agreements; Advisories on Stamp Duty and Capital Gains Tax and other property-related taxes.",
    services: [],
    sectorExpertise: [],
  },
  {
    id: "family-law",
    title: "Family Law",
    description: "The Firm provides responsive and personalized services to clients in relation to their family legal concerns. These services range from matrimonial disputes to succession and children-related matters.",
    details: "Specifically, the services we render in this Department include divorce, separation, child custody and access, guardianship, child maintenance, alimony, and spousal maintenance, distribution of matrimonial property, adoption, and guardianship, drafting of wills, setting up of trusts and succession matters. Our Team understands that this is a most personal and sensitive area of the law, where trust and confidentiality are critical, and strives to provide effective and compassionate representation in all areas of domestic relations through negotiation, mediation, litigation being the last resort. The Team deals with all matters with focus and pragmatism, being conscientious of the fact that the family related matters generate considerable stress for the client and have the greatest potential of having a lasting impact.",
    services: [],
    sectorExpertise: [],
  },
  {
    id: "policy-legislative-drafting",
    title: "Policy & Legislative Drafting",
    description: "We assist our clients in promoting policy change, contributing to the drafting of legislation, and managing regulatory risk that could affect their businesses. We regularly assist our clients in analyzing proposed legislation to keep them informed of the potential changes as well as how they may impact their operations.",
    details: "We have contributed to the development and drafting of a significant number of legislation in Kenya by offering legal advice and support to the policy-making institutions, government departments, legislators, regulatory authorities, and other stakeholders to draft legislation in the public finance, energy, public and administrative law, procurement, health and infrastructure sectors. Our support to clients includes the conduct of unique and quality research and analyses locally, while incorporating international best practices for each specific sector thereby ensuring that our drafting and review of the current or proposed policies and legislation can withstand public scrutiny. The Department is tasked with carrying out of gap analyses to determine legal lacunae with a view to improving the existing legislation. We are regularly consulted by government entities, both at the national and county levels, in respect of the drafting of new laws or subsidiary legislation. Further, we have advised various interest groups on certain (proposed) legislation.",
    services: [],
    sectorExpertise: [],
  },
  {
    id: "regional-integration",
    title: "Regional Integration",
    description: "We appreciate that globalization has made the world to be like a village. The strong economic, social, political, security and geographical motives have made States come together and establish institutions for a predictable international order. As a result, opportunities are availed both at the regional and international levels for clients.",
    details: "With the coming into force of the African Continental Free Trade Area (ACFTA), the department now finds itself advising clients beyond the traditional opportunities within the East African Community (EAC), the African Economic Community (AEC), the African Union (AU), the Southern African Development Community (SADC) or the Economic Communities of West African States (ECOWAS). It is also through this department that we help our clients who wish to enter into regional/international partnerships and agreements as a way of exhausting business opportunities available in the international markets. On a related note, we also ensure wholesome professional development through regional and international legal professional bodies like the East African Law Society (EALS), the Pan-African Lawyers Union (PALU), and the International Bar Association (IBA) all of which ensure that our lawyers remain well informed and connected at the global level.",
    services: [],
    sectorExpertise: [],
  },
  {
    id: "employment-labour",
    title: "Employment & Labour Relations",
    description: "We advise businesses, corporations and individuals across the spectrum of labor and employment-related matters. In addition, we provide legal advice to employers on compliance issues under various labor and employment laws with a view to strengthening our clients' internal structures to ensure compliance with the requirements of the law and limit risk exposure.",
    details: "In this regard, we assist our clients with the drafting of the individual employment contracts, Collective Bargaining Agreements (CBA's), Human Resource Policies, employee benefit plans, and other employment policies. We provide expertise across: Recruitment; Disciplinary process; Termination; Redundancy; Retirement; Equal opportunity issues; Employment discrimination claims; Collective bargaining negotiations; Human resource legal audit; Employment and Labour disputes; and Employment & labor relations policy advisories to State & private sector.",
    services: [],
    sectorExpertise: [],
  },
];
